### ISSUE TITLE
代理

### ISSUE THREAD

**Issue by HunterWangwei** [hominsu/freegpt35#3]
使用API方式的代理要怎么使用？
NEXT_PROXY直接填API：https://info.xxxx.com/extractProxyIp?regions=us&num=1&protocol=http&return_type=txt&lh=1&st=
来使用没有效果，一直返回：Error getting a new session, please try again later.
手动把代理获取出来再填进去使用就可以正常返回

**Comment by hominsu** [comment]
> 使用API方式的代理要怎么使用？ NEXT_PROXY直接填API：https://info.xxxx.com/extractProxyIp?regions=us&num=1&protocol=http&return_type=txt&lh=1&st= 来使用没有效果，一直返回：Error getting a new session, please try again later. 手动把代理获取出来再填进去使用就可以正常返回

it looks like u'r using some API-based proxy services, which can not be used directly in `NEXT_PROXY`. you need to pull out all the actual proxy deets - username, password, host, and port - and format them into `NEXT_PROXY` like: `http(s)://username:password@host:port` or `http(s)://@host:port.`

now only supports one proxy, but I might add multi-proxy support in the next update.
